export const tableData = [
  {
    name: "pen",
    qty: 24,
    minQty: 10,
    price: 10,
    tags: ["blue", "stationary"],
    notes: "fountain pens",
  },
  {
    name: "spoon",
    qty: 17,
    minQty: 20,
    price: 3.5,
    tags: ["silver", "kitchen", "metal"],
    notes: "kitchen spoons",
  },
  {
    name: "forks",
    qty: 37,
    minQty: 20,
    price: null,
    tags: ["silver", "kitchen", "metal"],
    notes: "",
  },
  {
    name: "toothbrush",
    qty: 137,
    minQty: 40,
    price: 5,
    tags: [],
    notes: "",
  },
  {
    name: "football",
    qty: 4,
    minQty: 10,
    price: 10,
    tags: ["sports"],
    notes: "High Gloss PU Synthetic leather stitched with Collar ankle mesh",
  },
];
